### ISSUE TITLE
Cant find system variables

### ISSUE THREAD

**Issue by fsi-inrotech** [simonl91/fanuc-karel-diagnostics#1]
Hi,
I have an issue with some specific systems variables, $HOSTS_CF for example. It detects it as an undefined variable.
If I compile the file via Ktrans manually there is no issue, but this is with a specific robot.ini file, like so _ktrans /config robot.ini file.pc_. 
Would it be possible to add a setting to set the path to an robot.ini file ? or have it placed in the .vcode folder ?

**Comment by simonl91** [comment]
Added settings for adding args to ktrans command.
Pushing fix now.

**Comment by simonl91** [comment]
v0.0.9 should be online now.
I have added settings for the extension that allows you to add a robot.ini file or any other ktrans command line argument:
![image](https://github.com/simonl91/fanuc-karel-diagnostics/assets/11440155/91b4a7e3-34ba-43b2-abef-49ce5d162e97)

**Comment by fsi-inrotech** [comment]
Nice thank you, it works with the pull path. 
Do you know if it would be possible to you the variables reference fx _${workspaceFolder}/${relativeFileDirname}/../build/robot.ini_

**Comment by simonl91** [comment]
I made 'KTRANS'  run in the context of the directory of the file you are editing.
In this way you can use a relative path. 
New version should be live now 0.1.0

**Comment by fsi-inrotech** [comment]
Thats great but i can see that an effect of that is that the .pc files now are located next to the .kl.
That is a bit annoying. I collect all the pc files in a single build folder to avoid clutter in my explorer.
would it be possible to move it so dynamic build folder or to the location it had before (v0.0.8)?
